### ISSUE TITLE
Console error using nextbus

### ISSUE THREAD

**Issue by AndyH-Numiko** [nwootton/MMM-UKLiveBusStopInfo#10]
Hi, I closed my other ticket (#9) as it had gone way off the original topic and I have better debug info now. I've removed MMM-Schedule from the equation entirely and the issue still occurs so it's nothing to do with that.

To recap, I'm having trouble getting the nextbus times to work reliably. Running MM in dev mode I can see console errors along these lines (sorry as MM is running on another machine via ssh I can't screengrab or copy and paste the errors):

`Uncaught TypeError: Cannot read property 'split' of null`

Expanding the object above that error in the console, I can see that `expected_departure_date` and `expected_departure_time` are both `null`.

There are values for `aimed_departure_time` , `best_departure_estimate`, and `date`

Here's my config.js:

```
                {
                        module:         'MMM-UKLiveBusStopInfo',        //Accurate times to Leeds
                        position:       'bottom_left',
                        header:         'To Leeds (realtime)',                  //Optional - delete this line to turn OFF the header completely
                        config: {
                                atcocode:               '3200YNA00515',                 // ATCO code for specific bus stop
                                app_id:                 '###',                             // TransportAPI App ID
                                app_key:                '###',                 // TransportAPI App Key
                                limit:                  5,                                      // Optional - Maximum results to display.
                                nextBuses:              'yes',
                                updateInterval:         60000,
                                showRealTime:           true,           // Optional - show realtime departure info
                                showDelay:              true,                   // Optional - show delay in minutes based on Real Time info vs Time table
                                showBearing:            true,
                                debug:                  true
                        }
                },
```

... let me know if there's anything I should look for in the console output that might help here?

**Comment by nwootton** [comment]
Ok, so the lack of ```expected_departure_date``` and ```expected_departure_time``` in the NextBus output is the issue and is down to the Bus Operator **NOT** supplying the information to the various parties.

Transport API state that "The NextBuses datasource will be used for bus stops outside of London, and
outside of a few other areas where we have access to more direct live bus data." - it is a _compromise_ solution to try and fill in the information gaps left by some service operators providing massive amounts of information (e.g. TfL) and some that don't/won't/can't provide enough. 

So if the bus operator isn't sending the complete data to the NextBus service. This then doesn't go into TransportAPI and hence the inability of the module to use the ```expected_departure_date``` and ```expected_departure_time``` to calculate the delays.

BUT, if the ```nextBuses``` is turned off, the module _should_ use the ```aimed_*``` and ```best_*``` values that perform exactly the same delay calculation - it's just potentially less accurate - but that is again dependent on the Bus operator data quality.

Alternatively, you can turn off the ```showDelay``` and not have the calculation run.

**Comment by nwootton** [comment]
I've created a new branch (I[ssue10](https://github.com/nwootton/MMM-UKLiveBusStopInfo/tree/Issue10)) with a potential 'fix' - but all it does is use the non NextBus data to fill the holes. Basically it falls back to the ```aimed_*``` and ```best_*``` values. ***BUT*** it will still cost you the extra NextBus credits even though you aren't using that data.

I'm a bit reluctant to put this into Master as it costs credits for no reason/benefit.

**Comment by AndyH-Numiko** [comment]
ok, thanks - that makes sense. I'll give that branch a try tonight but it sounds like I should change my config so that it's not even trying to use NextBus. I didn't realise you could still get an approximation of realtime data without it ... so, my config should probably be:

```
                {
                        module:         'MMM-UKLiveBusStopInfo',        //Accurate times to Leeds
                        position:       'bottom_left',
                        header:         'To Leeds (realtime)',                  //Optional - delete this line to turn OFF the header completely
                        config: {
                                atcocode:               '3200YNA00515',                 // ATCO code for specific bus stop
                                app_id:                 '###',                             // TransportAPI App ID
                                app_key:                '###',                 // TransportAPI App Key
                                limit:                  5,                                      // Optional - Maximum results to display.
                                nextBuses:              'no',
                                updateInterval:         60000,
                                showRealTime:           true,           // Optional - show realtime departure info
                                showDelay:              true,                   // Optional - show delay in minutes based on Real Time info vs Time table
                                showBearing:            true
                        }
                },
```

**Comment by nwootton** [comment]
TBH the whole thing is only as good as the data that the Bus operators supply to NextBuses and TransportAPI. Some are pretty good, some are next to useless.

The config looks OK - you could try running the old and the new configs side by side for a couple of hours and see if there's any significant difference.

**Comment by AndyH-Numiko** [comment]
The Issue10 branch works ok, it doesn't get stuck any more when expected_* is null.
From the api schema, it looks like you should expect `null` when there is no live data so I reckon this branch is a good idea to merge with master.

```
 "expected_departure_time": {
              "description": "Expected departure time of the service based on live data (or null if no live data is available)",
              "type": ["string", "null"]
            },
            "best_departure_estimate": {
              "description": "The aimed or expected departure time, whichever is available. Live data (expected) is taken as the best if both are available.",
              "type": "string"
            },
```
I have noticed using the transportapi that the expected times for my ATCO code get a real value when the bus is close to being due (which explains why I was sometimes able to have it working). So there would be some benefit for me to keep the nextBuses query on now that it doesn't get stuck.

What would be ideal, is if the module would show something other than 'On Time' when there was no expected_* data - so it's clear when realtime data is available?

e.g. if expected_* is `null`, instead of "7:56 (7:56) **ON TIME**" it would show "7:56 **SCHEDULED**" or just "7:56" ...

**Comment by nwootton** [comment]
I've added 2 things to the Issue 10 branch. 

1. additional logging to indicate that the NextBus info is missing and that the module is falling back to the timetable info.
2. The 'On Time' label will only be used when the NextBuses flag is TRUE, otherwise it will use 'Scheduled' - mostly to indicate the accuracy of the source data. It does ***NOT*** reflect any  other dynamic logic or code complexity.

What I don't have time to do at the moment is rewrite/refactor the entire inner logic around the availability of times/dates/timetables and the associated calculations for delays.

**Comment by AndyH-Numiko** [comment]
No problem, I've forked and will try to have a go myself over the weekend - I _think_ I can see a simpler way to handle it by setting another flag if expected_* is null ... will let you know how I get on.
