### ISSUE TITLE
Docs TransportAPI app id / key

### ISSUE THREAD

**Issue by harry-wood** [nwootton/MMM-UKLiveBusStopInfo#2]
I noticed you're including the app id & key from our docs in the README here. Just to let you know this one will be stopping working quite soon.

I don't think it really matters actually. Your README does a good a job of linking where folks need to go to register their own app id & key ( https://developer.transportapi.com ) .  But just to note that soon they _will_ need to do that, because that sample key won't work.

....
This looks neat by the way! So d'you have a mirror which tells you when the bus is coming? I want to see it!

**Comment by nwootton** [comment]
Many thanks Harry.

I'm still trying to figure out the physical part of the mirror, but the digital part is coming along. I've also built a Rail station version as well:

![mmm-uknationalrail](https://cloud.githubusercontent.com/assets/7591978/24352759/bcd10408-12e2-11e7-887f-6fcee16066db.jpg)

I will update the README in both modules to reflect the loss of the AppID and App Key.
