### ISSUE TITLE
API call costs

### ISSUE THREAD

**Issue by WelshRocketman** [nwootton/MMM-UKLiveBusStopInfo#3]
I have noticed that the bus info from transportapi costs 10 requests. Wondering if its worth noting that here anywhere?

**Comment by nwootton** [comment]
Hi WelshRocketman. I see what you mean. I suppose I could add the info here as well.

**Comment by nwootton** [comment]
Added note on README

**Comment by WelshRocketman** [comment]
Great. Sorry was about to look up the details for you. Very helpful module BTW.
