### ISSUE TITLE
showRealTime @ showDelay = True causes it to stick at 'Loading bus info'

### ISSUE THREAD

**Issue by Krisalexroberts** [nwootton/MMM-UKLiveBusStopInfo#4]
Hi, 

When I set the following:
      showRealTime: true,          // Optional - show realtime departure info
      showDelay: true,              // Optional - show delay in minutes based on Real Time info vs Time table
It gets stuck at 'loading'

When removed, it appears fine.

**Comment by nwootton** [comment]
Hi

I've just tried it at this end starting with everything off and then adding each option. It hasn't failed to load for me yet.

![screen shot 2017-04-02 at 09 02 40](https://cloud.githubusercontent.com/assets/7591978/24585495/ba2305c6-1783-11e7-9e5f-230fe42e8133.png)

Have you tried starting the mirror in dev mode and looking at the console? If so do you see any errors in the console?

Can you send me the ATCOCode - I'll look at the raw data from TransportAPI, it might be something missing in the JSON response that makes the calculation fail.

**Comment by nwootton** [comment]
@Krisalexroberts Did you solve your problem with this module? Is it still happening?

**Comment by nwootton** [comment]
Closing this as no further comments/replies
