### ISSUE TITLE
Module stops working after a while

### ISSUE THREAD

**Issue by orangebanana59** [nwootton/MMM-UKLiveBusStopInfo#6]
Hi,

My Pi is constantly on and I noticed that the module stops loading the bus times between midnight-1am and it won't refresh it until a restart the mirror.

Can you fix this issue or is it because of my particular bus?

**Comment by nwootton** [comment]
I can't comment on your particular bus because I don't have the ATCOcode as requested in troubleshooting item 6

Without that info I'm afraid I can't do anything.

**Comment by orangebanana59** [comment]
Apologies, the ATCOcode is: 490006830W.

**Comment by nwootton** [comment]
Ok I will try and have a look tonight or tomorrow. Couple of quick questions. Are you using the latest version (does the bus stop name show up as the header?). Are you using nextBuses? What is your refresh rate? It could be that the Bus Operator stops providing info to Transport API and I'm not handling that scenario.

**Comment by nwootton** [comment]
Ok, so the data coming back for the bus (W3 Finsbury Park Stn) appears to be fine. Not seeing any missing or corrupt data that might make the module fall over. 
Can you tell me what your config is so I can try it with that specific setup? Don't need the App_ID/App_Key!!!

**Comment by orangebanana59** [comment]
Thank you mate.
Here's my config without the AppID and Appkey:

{
			module: 'MMM-UKLiveBusStopInfo',
			classes: 'everyone default',
			position: 'center_bottom',
			config: {
			atcocode: 	'490006830W', 
			app_id: 	'.....', 	
			app_key: 	'.....', 	 
			limit: 		2, 
      			showRealTime: false,  
     			showDelay: false, 
		}

**Comment by nwootton** [comment]
OK, so I _think_ I know what is happening. The API is only returning a small subset of the data. I'm guessing the W3 route stops at some point, so the Operator stops sending departure info. As stuff is missing the module is stopping/erroring.

It's difficult to debug as it only happens at ~ midnight. I'll try and check my fix tonight to see if it works.

**Comment by orangebanana59** [comment]
Yes, I think that might be the issue. I put my Pi on automatic restart for every day at 1AM and what I noticed was that it was unable to load the buses even after that. When I restart it around 4AM, it works again.

**Comment by nwootton** [comment]
OK, so testing last night fixed one problem, but highlighted another. I think the error handling should now catch the issues of missing data at all levels and prevent the module from crashing.... BUT I'm not going to be able to test this until Monday night/Tuesday morning.

If you want to try it this weekend you can checkout the branch and run it yourself.

Remove or rename the current MMM-UKLiveBusStopInfo directory then:
```git clone -b Issue6 https://github.com/nwootton/MMM-UKLiveBusStopInfo.git``` 
```cd MMM-UKLIveBusStopInfo```
```npm install```

To revert to the original (master) just delete the (Issue6) MMM-UKLiveBusStopInfo directory and re-clone the master:
```git clone https://github.com/nwootton/MMM-UKLiveBusStopInfo.git``` 
```cd MMM-UKLIveBusStopInfo```
```npm install```

**Comment by orangebanana59** [comment]
Awesome, thank you! I will test this version for the weekend and get back to you with the results on Monday.

**Comment by orangebanana59** [comment]
Alright, so I gave it a go and it works perfectly! Thank you very much. 

This issue can be closed. :)

**Comment by nwootton** [comment]
Sweet. I'll merge this branch into the master tomorrow. Once that's done I'll let you know so you can switch back to the master branch. Once it's all working in the master I'll close the issue.

Thanks for the help sorting this out.

Nick

**Comment by nwootton** [comment]
Ok, so I've merged the Issue6 branch back into Master. Hopefully that will finally close this for you, but let me know if there are any other problems.

To revert to the original (master) just delete the (Issue6) MMM-UKLiveBusStopInfo directory and re-clone the master:
```
git clone https://github.com/nwootton/MMM-UKLiveBusStopInfo.git
cd MMM-UKLIveBusStopInfo
npm install
```
Nick

**Comment by nwootton** [comment]
Not heard anything, so I'll close this now.
