### ISSUE TITLE
Nextbuses

### ISSUE THREAD

**Issue by creatorsappox** [nwootton/MMM-UKLiveBusStopInfo#8]
Hi, I have set the nextBuses option to `no`, but the TranspotAPI still call nextBuses sometimes . Not as much if I set it to `yes`. Is there any way to stop that?
Many thanks, Bali

![transpotapi](https://user-images.githubusercontent.com/34719111/35348753-e72a56a4-0130-11e8-80c5-96b241d22270.jpg)

**Comment by nwootton** [comment]
I’ve no control over next buses calls, my module simply wraps the TransportAPI request. Looking at their documentation it states:

“The NextBuses datasource will be used for bus stops outside of London, and outside of a few other areas where we have access to more direct live bus data. NextBuses is a more expensive source and the charge is adjusted to 10 hits per request to reflect this. If you wish to avoid this hit charge and use only the other data sources, add a nextbuses=no parameter.”

As I’m just passing the variables through I can’t comment on any extraneous calls that might be made. It might pay you to ask the TransportAPI devs via their forums.
