### ISSUE TITLE
NextBuses toggle schedule

### ISSUE THREAD

**Issue by AndyHazz** [nwootton/MMM-UKLiveBusStopInfo#9]
In order to get more use of the NextBuses API, would it be possible to implement start/stop time ranges to set _nextBuses=yes_ on a schedule? I expect most people have a regular commute where they'd like more accurate bus times for a short period of each day ...

e.g.
```
nextBusesStart:    07.45
nextBusesStop:     08.15
```

If that could be combined with a general start/stop time for all updates then you could stop polling the API completely overnight (our buses don't run overnight anyway).

e.g.
```
start:    07.30
stop:     19.30
```

Based on those examples I think you could have it updating every 1 minute and still keep under the 1000 requests per day ...

**Comment by davidnesbitt7** [comment]
Yeah, have a look at the StartTime branch, I think he solved this there dude

**Comment by nwootton** [comment]
It's a prototype only on that brach. I never really had the time to work on it fully. Not even sure that the code in there works, so caveat emptor!

**Comment by AndyH-Numiko** [comment]
Well I'll be - seems to work for me!
Consider this a +1 for merging this into the master branch when you next get some time ...

**Comment by AndyH-Numiko** [comment]
In the end, I actually went with using https://github.com/ianperrin/MMM-ModuleScheduler

That lets me setup more than one module entry with different updateinterval and showRealTime/showDelay settings for different times of day, and switching off the module completely overnight, giving more control than the SmartTime branch, though it's a bit trickier to configure.

**Comment by AndyHazz** [comment]
After a month of occasional tweaking, I've been unable to get this working reliably with ModuleScheduler. It's close, but something seems to be stopping the nextbus live data. I'm not sure if this has anything to do with ModuleScheduler as it seems to get stuck even without this.

It either gets stuck showing 'Loading bus info ...' or shows no scheduled departures even when there are some using the live api documentation. Sometimes it works but not for long. I've been unable to tie it down to any particular time of day.

Could you see if there's anything suspicious with my ATCO code?

```
{
                        module:         'MMM-UKLiveBusStopInfo', 
                        position:       'bottom_left',
                        header:         'To Leeds', 
                        classes:        'scheduler',
                        config: {
                                module_schedule: {from: '15 7 * * *', to: '15 8 * * *' },
                                atcocode:               '3200YNA00515',                 // ATCO code for specific bus stop
                                app_id:                 '###',
                                app_key:                '###',
                                limit:                  5,
                                nextBuses:              "yes",
                                updateInterval:         60000,
                                showRealTime:           true,
                                showDelay:              true,
                                showBearing:            true,
                        }
                },
```

**Comment by nwootton** [comment]
Immediate response is that your nextBuses value should be 'yes' not "yes" and you have a trailing comma after showBearing - but those will depend on how strict the json parser in MM is.

TransportAPI has no issues with your ATCO - Marlborough Drive, Tadcaster going NE. Looks like it's route 840 going to Leeds Station. 

As I don't use ModuleScheduler, I'm afraid there's very little else I can suggest. Sometimes these issues are down to the bus operator not getting the info to the TransportAPI in a timely manner or even with incorrect data.

You can try adding ```debug: true ``` to the bottom of the config (after showBearing) and start the mirror in dev mode. That will show you all the messages flowing around the mirror modules and into the Bus module. 

Have you used all the daily credits with TransportAPI? NextBuses is EXPENSIVE (see README) - that might also explain why nothing is coming through.

**Comment by nwootton** [comment]
Have you checked the usage stats on the TransportAPI to see if the issues correspond with spikes shown there?

**Comment by AndyHazz** [comment]
I'll give those json tweaks a try tonight, thanks.

Yeah I've check the TransportAPI charts, I'm nowhere near using all the credits - they seem to show nextbusses getting one or two 20 point hits a day, when it should be using up 1200 points if it gets hit every minute for 1hr (I'm aware that'd take me over my daily limit, once it's working I'll tweak the schedule to fit the API limits).

Fingers crossed that debug config will shed some light.

**Comment by AndyHazz** [comment]
The json formatting tweaks looked good in a quick test last night, but by morning it had stopped working again ... I'll figure out how to start MM in dev mode and get some more tests setup later this week, then update this issue when I have more solid info.
